# Site settings
title: John Pearson
email: john.pearson@duke.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a research scientist in the Duke Institute for Brain Sciences. I apply
  machine learning techniques to the analysis of brain data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmxpearson.com" # the base hostname & protocol for your site
dukeurl: "http://www.duke.edu/~jmp33"
github_username:  jmxpearson

# Build settings
markdown: kramdown
